#
# info.pl
# TTYTTER extension to show information of a tweet
# Written by Thameera Senanayaka
# http://thameera.wordpress.com
# 
# Usage:
# Type in /info followed by the tweet id generated by ttytter.
# Example:
# /info d5
#

$addaction = sub {
	my @command = split(/ /, $_);
	
	if (lc($command[0]) eq '/info') {
		my $tweet_id = $command[1];
		my $tweet = &get_tweet($tweet_id);
		
		if (!$tweet->{'id_str'}) {
			print $stdout "-- Invalid tweet! --\n";
			return 1;
		}
		
		my $source_name = $source_url = &descape($tweet->{'source'});
		$source_name =~ s/<.*?>//g;
		$source_url =~ s/(<.*?")//;
		$source_url =~ s/(".*>)//;
		$source_url = " ( " . $source_url . " )";
		$source_url = '' if (lc($source_name) eq 'web');
		
		my $id = &descape($tweet->{'id_str'});
		my $author = &descape($tweet->{'user'}->{'screen_name'});
		my $tw_url = "http://twitter.com/" . $author . "/status/" . $id;

		eval 'use Date::Parse; return 1' || print "xxxxxxxx";
		my $createdat = &descape($tweet->{'created_at'});
		my $timezone = &descape($tweet->{'time_zone'});
		my $time = str2time($createdat, $timezone);
		my ($sec,$min,$hour,$day,$mon,$year) = localtime($time);
		$timestr = sprintf '%d/%d/%d %02d:%02d:%02d', $day, $mon+1, $year+1900, $hour, $min, $sec;

		print "-- Time: " . $timestr . " --\n";
		print "-- Source: " . $source_name . $source_url . " --\n";
		print "-- Link to tweet " . $tw_url . " --\n";
		return 1;
	}
	
	return 0;
}
