#
# pocket.pl
# TTYTTER extension to add links to Pocket
# Written by Thameera Senanayaka
# http://thameera.wordpress.com
#
# How it works
# You need to place a file named .pocket in the extension's 
# directory. This file should contain your Pocket username and
# password in two lines.
# The extension will add the first link found in the tweet's text
# to pocket. If no link is found, the tweet's link is added.
# 
# Usage:
# Type in /pocket followed by the tweet id generated by ttytter.
# Example:
# /pocket d5
#

use URI::Escape;

$addaction = sub {
    my @command = split(/ /, $_);

    if (lc($command[0]) eq '/pocket')  {

		$id = $command[1];
        my $tweet=&get_tweet($id);
        if (!$tweet->{'id_str'}) {
            print $stdout "-- Invalid tweet id --\n";
            return 1;
        }
		my @cred = split('\n', `cat .pocket`);

		my $text = &descape($tweet->{'text'});
		my $twurl = uri_escape("http://twitter.com/$tweet->{'user'}->{'screen_name'}/statuses/$tweet->{'id_str'}");

		my $url = '';
		while ($text =~ s#(h?ttp|h?ttps)://([a-zA-Z0-9_~/:%\-\+\.\=\&\?\#,]+)##){
			$url = $1 . "://$2";
			$url = "h$url" if ($url =~ /^ttps?:/);
			$url =~ s/[\.\?]$//;
			$url = uri_escape($url);
		}
		$url =  $twurl if ($url eq '');

		#my $purl = "https://readitlaterlist.com/v2/add?username=" . $cred[0] . "&password=" . $cred[1] . "&apikey=" . $cred[2]  . "&url=" . $url . "&title=" . uri_escape($tweet->{'text'});
		my $purl = "https://readitlaterlist.com/v2/add?username=" . $cred[0] . "&password=" . $cred[1] . "&apikey=c4bIbA99g423fX70lkdf26fd79p6y416&url=" . $url . "&title=" . uri_escape($text);
		
		my $err = `curl -s \"$purl\"`;

	 	my @msg = split(/ /, $err);
		if ($msg[0] eq '200') {
			print "Added to Pocket!\n";
		} else {
			print "Couldn't add to Pocket: " . $err . "\n";
		}
		return 1;
    }
    return 0;
};
